name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Sỹ Năm Mystic
        run: |
          curl -L https://synam.online
          curl -L https://sybinh.onrender.com
          curl -L https://sybinh.onrender.com/api/health
